# Generated by Django 5.0.6 on 2025-09-19 17:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_bulletin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulletin',
            options={},
        ),
        migrations.RemoveField(
            model_name='bulletin',
            name='readings_text',
        ),
        migrations.AddField(
            model_name='bulletin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bulletin',
            name='gospel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='reading_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='reading_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='responsorial_psalm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
