# Generated by Django 5.0.6 on 2025-09-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_bulletin_options_remove_bulletin_readings_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='day_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='gospel_citation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='gospel_optional',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='gospel_optional_citation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='memorial',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='psalm_citation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='psalm_optional',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='psalm_optional_citation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='psalm_optional_refrain',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='psalm_refrain',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='reading_1_citation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='reading_1_optional',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='reading_1_optional_citation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='reading_2_citation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='reading_2_optional',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='reading_2_optional_citation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='season',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
