# Generated by Django 5.0.6 on 2025-09-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_bulletin_day_title_bulletin_gospel_citation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
