# Generated by Django 5.0.6 on 2025-09-30 20:28

# gallery/migrations/0006_load_harvest_events.py
from django.db import migrations
import datetime

def load_events(apps, schema_editor):
    HarvestEvent = apps.get_model("gallery", "HarvestEvent")
    events = [
        ("Proposed Selected Themes", datetime.date(2025, 6, 1), ""),
        ("Campaign & Offering to pick theme", datetime.date(2025, 6, 8), ""),
        ("Unveiling of Harvest Banner", datetime.date(2025, 6, 22), ""),
        ("Currency Harvest – ₦20, ₦50", datetime.date(2025, 7, 6), ""),
        ("Currency Harvest – ₦100, ₦200", datetime.date(2025, 7, 13), ""),
        ("Currency Harvest – ₦500, ₦1,000", datetime.date(2025, 7, 20), ""),
        ("Currency Harvest – All foreign currency", datetime.date(2025, 7, 27), ""),
        ("Fruit Harvest", datetime.date(2025, 8, 3), ""),
        ("Cultural Sunday", datetime.date(2025, 8, 17), ""),
        ("Club/Sports Day", datetime.date(2025, 9, 7), ""),
        ("Farmers/Traders/Goods/Professionals", datetime.date(2025, 9, 21), ""),
        ("Children/Youth Day", datetime.date(2025, 10, 12), ""),
        ("Launching of Harvest Brochure", datetime.date(2025, 10, 26), ""),
        ("Harvest Day", datetime.date(2025, 11, 9), ""),
    ]
    for title, date, desc in events:
        HarvestEvent.objects.create(title=title, date=date, description=desc)

def unload_events(apps, schema_editor):
    HarvestEvent = apps.get_model("gallery", "HarvestEvent")
    HarvestEvent.objects.all().delete()

class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0005_harvestevent"),  # ← Must point to the model creation migration
    ]

    operations = [
        migrations.RunPython(load_events, unload_events),
    ]